datasources:
  default:
    url: jdbc:postgresql://localhost:5432/archimedes
    username: postgres
    password: verysecret
    driverClassName: org.postgresql.Driver
    minimumIdle: 10
    maximumPoolSize: 30
